import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/common/navbar";
import ReactQueryProvider from "@/components/common/react-query-provider";
import {Toaster} from "@/components/ui/toaster";
import AuthProvider from "@/components/common/auth-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <AuthProvider>
            <div className="bg-white text-black flex flex-col min-h-screen">
              <Navbar />
              <div>{children}</div>
              <Toaster />
            </div>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
